head_camera:
  enable_zmq: true
  enable_webrtc: false
  webrtc_port: 6002
  webrtc_codec: h264
  zmq_port: 5555
  depth_zmq_port: 5558
  raw_depth_zmq_port: 5559
  depth_scale_m_per_unit: 0.001
  binocular: false
  type: realsense
  image_shape:
  - 480
  - 640
  fps: 30
  enable_depth: true
  serial_number: '242322076480'
left_wrist_camera:
  type: uvc
  enable_zmq: false
  enable_webrtc: false
  binocular: false
right_wrist_camera:
  type: uvc
  enable_zmq: false
  enable_webrtc: false
  binocular: false
